---
- name: Setup Project
  hosts: 127.0.0.1
  gather_facts: false

  tasks:
    - name: Create DB
      block:
      - name: Check the DB exists
        stat:
          path: "{{playbook_dir }}/../../{{ db_path }}"
        register: db_file

      - name: Create the DB file
        command: touch {{playbook_dir }}/../../{{ db_path }}
        when: not db_file.stat.exists

      - name: Create DB tables
        command: python3 -m "{{playbook_dir }}/../../python/api_data_pipeline/storage"